[package]
name = "rfbutton"
version = "0.1.0"
authors = ["Andrew Walbran <qwandor@gmail.com>"]
edition = "2021"
description = "A library for decoding 433 MHz RF remote codes."
repository = "https://github.com/qwandor/rfbutton/"

[dependencies]
