[package]
name = "rfbutton"
version = "0.1.0"
edition = "2021"
description = "A library for decoding 433 MHz RF remote codes."
authors = ["Andrew Walbran <qwandor@gmail.com>"]
repository = "https://github.com/qwandor/rfbutton/"
keywords = ["rf", "433mhz"]
categories = ["hardware-support", "parser-implementations"]

[dependencies]
thiserror = "1.0.30"
